version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: Qu4rku5
      POSTGRES_DB: quarkus_qute
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    restart: always
    command:
      - "start-dev"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/quarkus_qute
      KC_DB_USERNAME: quarkus
      KC_DB_PASSWORD: Qu4rku5
      KC_HOSTNAME: localhost
    ports:
      - "9090:8080"
    depends_on:
      - db
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  postgres_data:
  keycloak_data:
